version: '3.8'

services:
  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    ports:
      - "18080:18080"
    restart: unless-stopped
    environment:
            - LOG_LEVEL=INFO
            - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
            - NIFI_REGISTRY_FLOW_PROVIDER=file #flow information is stored on the local file system
            - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    volumes:
            - /ws-storage/nifi_registry/database:/opt/nifi-registry/nifi-registry-current/database
            - /ws-storage/nifi_registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    user: "root" # Use root user for updating volume - This Volume is for persistence
    networks:
      - nifi_network

  nifi:
    image: apache/nifi:latest
    env_file: .env
    ports:
      - 8443:8443 
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=$NIFI_USER
      - SINGLE_USER_CREDENTIALS_PASSWORD=$NIFI_PWD
    links:
      - nifi-registry
    volumes:
      - /ws-storage/nifi/state:/opt/nifi/nifi-current/state
      - /ws-storage/nifi/db:/opt/nifi/nifi-current/database_repository
      - /ws-storage/nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
      - /ws-storage/nifi/content:/opt/nifi/nifi-current/content_repository
      - /ws-storage/nifi/provenance:/opt/nifi/nifi-current/provenance_repository
    user: "root" # Use root user for updating volume - This Volume is for persistence
    networks:
      - nifi_network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - /ws-storage/mongodb/data:/data/db
    networks:
      - nifi_network

networks:
  nifi_network:
